networks:
  bigdata-net:
    external: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:
  scheduler:
    networks:
      - bigdata-net

  triggerer:
    networks:
      - bigdata-net

  postgres:
    networks:
      - bigdata-net

  webserver:
    networks:
      - bigdata-net

